### ISSUE TITLE
DirectoryFMU.java tries to load win64 by default on win64 system.

### ISSUE THREAD

**Issue by clagms** [INTO-CPS-Association/org.intocps.maestro.fmi#1]
The function generateLibraryFile, when invoked on a win64 system, will try to load a 64 bit FMU.

Possible solutions:
1. The least common denominator architecture should be picked for each FMU, by looking at all FMUs. For example, if I have 3 fmus win64 and win32, and 1 fmu win32, then win32 should be chosen as preferred architecture for all FMUs.
1. The user specifies which is the preferred architecture for each FMU through the interface.
1. On win64, if I add an FMU that only has win32, then it should be marked as incompatible. Currently the intocps app says that it is compatible, but then the user get's an error when running the co-simulation.

Log of the error is:
````
ERROR [NanoHttpd Request Processor (#1)] (DirectoryFmu.java:120) - Fmu do not conform to the standard. Unable to obtain modelIndentifier 'Scenario' for co-simulation, defaulting to archieve name 'Scenario' 
WARN [NanoHttpd Request Processor (#1)] (DirectoryFmu.java:121) - Attempting to recover loading of the library by setting modelIndentifier='Scenario' 
ERROR [NanoHttpd Request Processor (#1)] (RequestProcessors.java:330) - Internal error in initialization 
org.intocps.orchestration.coe.AbortSimulationException: An FMU library didn't load 
{Scenario} library does not exist: C:\Users\clagm\AppData\Local\Temp\Scenario7159337731562902037\binaries\win64\Scenario.dll 
at org.intocps.orchestration.coe.scala.CoeInitialize$.initialize(CoeInitialize.scala:110) 
at org.intocps.orchestration.coe.scala.Coe.initialize(Coe.scala:169) 
at org.intocps.orchestration.coe.httpserver.RequestProcessors.processInitialize(RequestProcessors.java:321) 
at org.intocps.orchestration.coe.httpserver.RequestHandler.initialize(RequestHandler.java:362) 
at org.intocps.orchestration.coe.httpserver.RequestHandler.handleRequest(RequestHandler.java:212) 
at org.intocps.orchestration.coe.httpserver.NanoWSDImpl.serveHttp(NanoWSDImpl.java:70) 
at fi.iki.elonen.NanoWSD.serve(NanoWSD.java:861) 
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:927) 
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:194) 
at java.lang.Thread.run(Unknown Source) 
````

**Comment by CThuleHansen** [comment]
Hi, thank you for the issue report and the solution proposals.
This is something that needs to be addressed. I will try to answer your possible solutions, and hopefully we'll conclude on something.
1. It depends on the architecture of the JVM used to run Maestro on. The architecture of the JVM must match the architecture of the FMU. Therefore, in your example, Maestro must be executed using a 32-bit JVM. An option is a bridge process invoked with some RPC, but this is out of scope currently.
2. Valid option, but again depends on the JVM.
3. win32 FMUs can run on win64 systems, so it seems like an unnecessary constraint due to the reasons also noted above.

My idea for solution:
1. Make Maestro return a much better error
2. If using the into-cps application and Maestro has been launched, then query Maestro for the JVM version. If it does not match with the FMUs, then disable the simulate button. 

Maestro is used without the INTO-CPS Application, so 1. definitely makes sense.
2. is nice-to-have.

**Comment by CThuleHansen** [comment]
Adressed in: https://github.com/INTO-CPS-Association/org.intocps.maestro.fmi/commit/7c3f37954ab67a34ca83826016d407cb429605ad

**Comment by CThuleHansen** [comment]
Tested, and will be released with next tool bundle release.
